language: go
go:
- '1.13'
#service:  Docker Compose it is not required for nei-elasticsearch
#- docker
jobs:
  include:

# TESTING
  - stage: testing Linux and Windows
    os: linux
    script: make clean validate test
    on:
      tags: true
  - os: windows
    script:
    - go test ./src/

# CREATING THE RELEASES
  - stage: creating Realease
    os: linux
    addons:
      apt:
        update: true
        packages:
        - rpm
        - ruby
        - ruby-dev
        - rubygems
        - build-essential
    script:
    - gem install --no-document fpm
    - make package
    deploy:
      provider: releases
      file_glob: true
      api_key:
        secure: d+2f8ycKVPKUy1xqfoR+LG+CxrTJEtS6PuKxbUaxdQkXdR8j6VApgu4uwudoKfflr0aHI8AnYXO+gSSPMQay07NSyw0it+bSgZBdDkdGrCHlTvh1hWbh6RKHJr6MPHgkpg8CXkvvzTnN8TPzk7c6j19W6eptAHJneRcskzmP2qZBC6rqHs15F60dr22yq1HLBJZawv05HOBjllK9Q1BPFZHqhM/Y0wOFKnE5wZHMLaACu+IVpE//38rr4m4/nVAZ3Pp/ytz6yI4OBOuVR7+kLPaLFGqDjLRDL+nQ6kQCp+2dNJXycWpPP8M5EtzpMlTLVveLqWqGJCyUmjN05C5pKCZQ7M4X41xyX9bcTPibR1V9pTD+i0zmDCfGzWx+47vds8XOAd+B0zMpc2IX7hhbYQ8cqBQeaV+XjzRe62SKxUDRbFMZaw5jbystg/Kck2m8aH7AiHQu7NBMAYZwqj4kgzJRTS1U+7wgTOIVJ8Pen5WeALhIUprWsjhw9Rhe78olJKaydcYiKEK7LWTe1dKCEpamqIN+hUL+P9MRXwVGGMF71TV7t7kIAjY6KEZqpzG/TiCh0y9A/BZMOPSZHGgRMFHZGtVr+KIqO0jX19QRh92e5uT5IgJ5MvwJQAGnc+Pt8EkoRcrelMURW8FKWb2Ho/7eOFEq2WflMmVc1aoyF2A=
      file:
      - "./target/bin/linux_amd64/nri-*"
      - "./target/packages/deb/*.deb"
      - "./target/packages/rpm/*.rpm"
      - "./target/packages/tarball/*.tar.gz"
      skip_cleanup: true

  - stage: creating Realease
    os: windows
    env:
    - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
    before_script:
    - powershell Install-WindowsFeature Net-Framework-Core
    - cinst -y wixtoolset
    script:
    - openssl aes-256-cbc -K $encrypted_beab01555d2d_key -iv $encrypted_beab01555d2d_iv -in autosigned.pfx.enc -out ./pkg/windows/nri-amd64-installer/mycert.pfx -d
    - export PATH=$MSBUILD_PATH:$PATH
    - go build -v -o ./target/bin/windows_amd64/nri-elasticsearch.exe  ./src/
    - cd ./pkg/windows/nri-amd64-installer/ ; msbuild.exe ./nri-installer-travis.wixproj
    - ls -R ../*
    deploy:
      provider: releases
      file_glob: true
      api_key:
        secure: d+2f8ycKVPKUy1xqfoR+LG+CxrTJEtS6PuKxbUaxdQkXdR8j6VApgu4uwudoKfflr0aHI8AnYXO+gSSPMQay07NSyw0it+bSgZBdDkdGrCHlTvh1hWbh6RKHJr6MPHgkpg8CXkvvzTnN8TPzk7c6j19W6eptAHJneRcskzmP2qZBC6rqHs15F60dr22yq1HLBJZawv05HOBjllK9Q1BPFZHqhM/Y0wOFKnE5wZHMLaACu+IVpE//38rr4m4/nVAZ3Pp/ytz6yI4OBOuVR7+kLPaLFGqDjLRDL+nQ6kQCp+2dNJXycWpPP8M5EtzpMlTLVveLqWqGJCyUmjN05C5pKCZQ7M4X41xyX9bcTPibR1V9pTD+i0zmDCfGzWx+47vds8XOAd+B0zMpc2IX7hhbYQ8cqBQeaV+XjzRe62SKxUDRbFMZaw5jbystg/Kck2m8aH7AiHQu7NBMAYZwqj4kgzJRTS1U+7wgTOIVJ8Pen5WeALhIUprWsjhw9Rhe78olJKaydcYiKEK7LWTe1dKCEpamqIN+hUL+P9MRXwVGGMF71TV7t7kIAjY6KEZqpzG/TiCh0y9A/BZMOPSZHGgRMFHZGtVr+KIqO0jX19QRh92e5uT5IgJ5MvwJQAGnc+Pt8EkoRcrelMURW8FKWb2Ho/7eOFEq2WflMmVc1aoyF2A=
      file:
      - "./target/bin/windows_amd64/nri-"
      - "./bin/Release/*"
      skip_cleanup: true
#      on:
#        tags: true